### ISSUE TITLE
'static_cast': cannot convert from 'float' to 'ImGuiDir_'	imguibuilder\main\build_config.cpp	233	

### ISSUE THREAD

**Issue by graysuit** [Code-Building/ImGuiBuilder#10]
These 2 lines were
```cpp
			case 23:
				custom_gui_style.WindowMenuButtonPosition	= static_cast<ImGuiDir_>( std::stof( line ) );
				break;
			case 24:
				custom_gui_style.ColorButtonPosition		= static_cast<ImGuiDir_>( std::stof( line ) );
				break;
```

but when I used `(ImGuiDir)(...)`, it build and run fine.
like:
```cpp
			case 23:
				custom_gui_style.WindowMenuButtonPosition	= (ImGuiDir)( std::stof( line ) );
				break;
			case 24:
				custom_gui_style.ColorButtonPosition		= (ImGuiDir)( std::stof( line ) );
				break;
```

But at end, when I try to generate code, it shows this error in image.
![Capture](https://user-images.githubusercontent.com/54432616/126875169-573bc9e9-76f0-48cc-acd7-9fd6d5b09637.PNG)

**Comment by SmoLL-iCe** [comment]
I did tests here in all ways and I didn't have the same problem, I tried with several controls and settings and it didn't give an error.
static_cast is correct, it's from a float to an enum, it doesn't make sense for this to be the cause of the problem.

**Comment by graysuit** [comment]
Not sure why, but this error do appear on my PC, but not when I compile it via github vps.
The compiled files are now working fine without giving any error.
https://github.com/Code-Building/ImGuiBuilder/pull/11

**Comment by Slluxx** [comment]
Appears on my pc too. Same error. Everything up to date

**Comment by Naeemullah1** [comment]
What is the solution to this problem? Still not compiling. Same two errors in build. I checked all configurations x64 release and build, x86 release and build and also the OpenGL2. 
No other errors, only these 2 exist.
I am using visual studio 2019 with all SDKs, correctly installed.
