### ISSUE TITLE
Debug Assertion Failed!

### ISSUE THREAD

**Issue by Zawaer** [Code-Building/ImGuiBuilder#12]
Help, when i try to save or generate the code, i get this error:
![ImGuiBuilder! 24 9 2021 17 22 36](https://user-images.githubusercontent.com/79928133/134690809-fb2bb54a-5751-4fdd-828d-ce018263140f.png)

**Comment by vanguardloaders** [comment]
I also get this message when trying to do the same thing.

**Comment by vanguardloaders** [comment]
solved!  to solve this problem you need to select the Build Mode to OpenGL2

**Comment by Zawaer** [comment]
Thanks! I'll try it! 👍
