### ISSUE TITLE
Confusing reinterpret_cast

### ISSUE THREAD

**Issue by wmcnamara** [Code-Building/ImGuiBuilder#7]
Hi! I'm trying to understand the code in this application, and noticed a section that is confusing me.

In the `the_window.cpp` file, there is this code starting at line 144:
```cpp
if ( m_func_draw )
    reinterpret_cast<void( __stdcall* )( void )>( m_func_draw )( );
``` 
What is this doing? If its no trouble, could a comment be added to this? 😄

**Comment by SmoLL-iCe** [comment]
the_window.cpp file
contains the window creation class, the function that will be used to draw in that window is passed as an argument in the class's oncreate. 
https://github.com/Code-Building/ImGuiBuilder/blob/main/ImGuiBuilder/main.cpp#L7

the function pointer is associated with a member of the class that is called in the routine to draw everything. 
https://github.com/Code-Building/ImGuiBuilder/blob/main/ImGuiBuilder/main/the_window.cpp#L145

it just checks if the pointer is valid and calls it as a function.
if you comment on that, everything from the imgui stops showing in the window.

**Comment by wmcnamara** [comment]
Gotcha!

Also, I didnt mean comment the line *out* haha. 

I just meant adding a comment explaining the line. Thanks for taking the time to explain it!
