### ISSUE TITLE
Prebuilt binaries

### ISSUE THREAD

**Issue by alwendya** [Code-Building/ImGuiBuilder#8]
I've problem building GLFW (I use Imgui with SDL2 rendered) so I can't test ImGuiBuilder.
I would like to know if you can publish a release with compiled exe files for windows.

BTW, IMGui Builder seems amazing and I really want to test it...
Thanks in advance,
Grégory

**Comment by SmoLL-iCe** [comment]
we don't put a compiled version, because in some places it's been published, they don't accept it. 
what's your problem in to compiling with GLFW ?
